import type { Metadata } from "next";
import { DM_Sans, Bebas_Neue } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footerv2/Footerv2";

const dmSans = DM_Sans({
  subsets: ["latin"],
  variable: "--font-dm-sans",
});

const bebasNeue = Bebas_Neue({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-bebas",
});

const horizon = localFont({
  src: "./fonts/horizon.otf", // Check your exact file path
  variable: "--font-horizon",
});

export const metadata: Metadata = {
  title: "Charcoalite | Bio Charcoal",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang="en"
      className={`${dmSans.variable} ${bebasNeue.variable} ${horizon.variable}`}
    >
      <body className="bg-charcoal text-white antialiased">
        <Header />
        <main className="min-h-screen">{children}</main>
        <Footer />
      </body>
    </html>
  );
}
